name: robert
favicon: null
layout_spectrum: 0.99792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343434'
    - '#62584c'
    - '#8c816f'
    - '#000000'
    - '#d2ccb4'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
